---
resources:
  - name: resource-scripts
    type: git
    source:
      uri: https://github.com/gpltaylor/concourse-demo.git
      branch: master
  - name: resource-app
    type: git
    source:
      uri: https://github.com/gpltaylor/react-router-workshop.git
      branch: master


jobs:
  - name: job-test-app
    public: true
    plan:
      - get: resource-app
      - get: resource-scripts
        trigger: true
      - task: web-app-tests
        file: resource-scripts/tasks/taska.yml
